apiVersion: apps/v1
kind: Deployment
metadata:
  name: mars-deploy-go-hello
  namespace: mars-deploy-fail
  labels:
    app: go-hello
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-hello
  template:
    metadata:
      labels:
        app: go-hello
    spec:
      containers:
        - name: go-hello
          image: {{image_url}}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MY_NODE_IP
                valueFrom:
                  fieldRef:
                    fieldPath: spec.hostIP
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      imagePullSecrets:
        - name: volces-sr-secret

---

apiVersion: v1
kind: Service
metadata:
  name: mars-deploy-go-hello
  namespace: mars-deploy-fail
spec:
  selector:
    app: go-hello
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080